In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [93]:
df=pd.read_csv("/content/drive/MyDrive/ml dataset/train.csv")

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
(df.isnull().sum()/df.shape[0])*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [10]:
age_missing_index = df[df['Age'].isnull()].index.to_list()

In [13]:
train_1 = df.copy()
train_1["Age"].fillna(30,inplace=True)
train_1.isnull().sum()

<ipython-input-13-9353135292d7>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  train_1["Age"].fillna(30,inplace=True)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [14]:
train_1.iloc[age_missing_index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,30.0,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,30.0,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,30.0,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,30.0,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,30.0,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,30.0,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,30.0,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,30.0,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,30.0,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,30.0,1,2,W./C. 6607,23.4500,NaN,S

In [18]:
#imputing with a constant
from sklearn.impute import SimpleImputer
train_constant =df.copy()

In [19]:
#setting strategy to 'constant'
cons_imputer = SimpleImputer(strategy='constant',fill_value=-1)
train_constant.iloc[:,:]=cons_imputer.fit_transform(train_constant)

In [20]:
#missing value count
train_constant.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [21]:
train_constant.iloc[age_missing_index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,-1.0,0,0,330877,8.4583,-1,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,-1.0,0,0,244373,13.0000,-1,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,-1.0,0,0,2649,7.2250,-1,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,-1.0,0,0,2631,7.2250,-1,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,-1.0,0,0,330959,7.8792,-1,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,-1.0,0,0,2629,7.2292,-1,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,-1.0,8,2,CA. 2343,69.5500,-1,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,-1.0,0,0,345777,9.5000,-1,S
878,879,0,3,"Laleff, Mr. Kristo",male,-1.0,0,0,349217,7.8958,-1,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,-1.0,1,2,W./C. 6607,23.4500,-1,S

In [22]:
train = df.copy()
imputer = SimpleImputer(strategy='mean')
train['Age']=imputer.fit_transform(train[['Age']])
train.iloc[age_missing_index]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,29.699118,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S

In [28]:
df2=pd.read_csv("/content/drive/MyDrive/ml dataset/iris.csv")
df2

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.4           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.3          0.2     setosa
4             5.1          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [30]:
x = df2.drop("species", axis=1)
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.4           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.3          0.2
4             5.1          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [31]:
y = df2["species"]
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [43]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
df2["New species"] = lb.fit_transform(df2["species"])
df2

,sepal_length,sepal_width,petal_length,petal_width,species,New species
0,5.1,3.5,1.4,0.2,setosa,0
1,4.9,3.4,1.4,0.2,setosa,0
2,4.7,3.2,1.3,0.2,setosa,0
3,4.6,3.1,1.3,0.2,setosa,0
4,5.1,3.6,1.4,0.2,setosa,0
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,2
146,6.3,2.5,5.0,1.9,virginica,2
147,6.5,3.0,5.2,2.0,virginica,2
148,6.2,3.4,5.4,2.3,virginica,2
149,5.9,3.0,5.1,1.8,virginica,2

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [34]:
y_test

21         setosa
61     versicolor
102     virginica
101     virginica
78     versicolor
115     virginica
76     versicolor
117     virginica
63     versicolor
33         setosa
91     versicolor
111     virginica
41         setosa
138     virginica
81     versicolor
116     virginica
20         setosa
26         setosa
62     versicolor
30         setosa
103     virginica
16         setosa
55     versicolor
142     virginica
27         setosa
59     versicolor
39         setosa
28         setosa
13         setosa
128     virginica
Name: species, dtype: object

In [50]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

# Assuming 'df' is your DataFrame and 'species' is your target column

# Initialize LabelEncoder
lb = LabelEncoder()

# Fit and transform the 'species' column to create numerical labels
df["New species"] = lb.fit_transform(df["species"])

# Define your features (X) and target (y)
# Assuming 'x' contains your feature columns
# Use the encoded 'New species' column as the target
y = df["New species"]

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

# Initialize and train the Linear Regression model
lrg = LinearRegression()
lrg.fit(x_train, y_train)

# Evaluate the model
lrg.score(x_train, y_train) * 100

93.52548338200421

ValueError: could not convert string to float: 'setosa'

In [51]:
# lrg = LinearRegression()
# lrg.fit(x_train,y_train)
# lrg.score(x_test,y_test)*100

In [52]:
# lrg.score(x_test,y_test)*100

In [55]:
y_pred_lrg = lrg.predict(x_test)

In [56]:
y_pred_lrg

array([-0.05644714, -0.01742393,  1.43627054,  0.86209035, -0.07629715,
       -0.15050745,  1.57421278,  1.60221441, -0.1318247 ,  1.19960794,
        1.92876055, -0.08595669,  1.20067945,  1.76199275,  0.14997896,
       -0.03703231,  1.28522488,  2.12382051,  0.03412039,  0.01674567,
        1.06234969,  1.28489261,  1.03725855,  1.60750443,  1.78489913,
        1.84881992,  1.71884166,  1.39613286,  1.99340706, -0.04305441])

In [53]:
y_test

1      0
42     0
72     1
79     1
9      0
33     0
83     1
70     1
22     0
75     1
128    2
4      0
58     1
101    2
44     0
20     0
61     1
144    2
6      0
30     0
82     1
55     1
69     1
106    2
121    2
112    2
110    2
85     1
120    2
40     0
Name: New species, dtype: int64

In [60]:
from sklearn.linear_model import LogisticRegression
lgrg = LogisticRegression()
lgrg.fit(x_train,y_train)
y_train_prediction = lgrg.predict(x_train)

In [59]:
from sklearn.metrics import accuracy_score
accuracy_score(y_train,y_train_prediction)*100

99.16666666666667

In [70]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report


data = {
    'pclass': [1, 2, 3, 1, 2, 3, 1, 2, 3, 1],
    'age': [22, 38, 26, 27, 30, 35, 24, 28, 34, 32],
    'gender': [1, 0, 0, 1, 0, 1, 1, 0, 0, 1]
}
train = pd.DataFrame(data)


X = train[['pclass', 'age']]
y = train['gender']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


logistic_model = LogisticRegression()
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)


dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)
y_pred_dt = dt_model.predict(X_test)


print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_logistic))
print("Logistic Regression Classification Report:\n", classification_report(y_test, y_pred_logistic))

print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Decision Tree Classification Report:\n", classification_report(y_test, y_pred_dt))

Logistic Regression Accuracy: 0.5
Logistic Regression Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.00      0.00      0.00         0

    accuracy                           0.50         2
   macro avg       0.50      0.25      0.33         2
weighted avg       1.00      0.50      0.67         2

Decision Tree Accuracy: 0.0
Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       2.0
           1       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [82]:
# import pandas as pd


import pandas as pd


train = pd.read_csv('/content/drive/MyDrive/ml dataset/iris.csv')


print("Original DataFrame:")
print(train.head())


if 'age' not in train.columns:
    print("Column 'age' not found. Please ensure your dataset contains an 'age' column.")
else:

    train['age'] = train.groupby('pclass')['age'].transform(lambda x: x.fillna(x.mean()))

    print("Modified DataFrame:")
    print(train)

Original DataFrame:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.4           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.3          0.2  setosa
4           5.1          3.6           1.4          0.2  setosa
Column 'age' not found. Please ensure your dataset contains an 'age' column.

In [85]:

import pandas as pd


train = pd.read_csv('/content/drive/MyDrive/ml dataset/iris.csv')


print("Original DataFrame:")
print(train.head())

if 'pclass' not in train.columns or 'age' not in train.columns:
    print("Columns 'pclass' and 'age' must exist in the dataset.")
else:

    train['age'] = train.groupby('pclass')['age'].transform(lambda x: x.fillna(x.mean()))
    train['pclass_normalized'] = (train['pclass'] - train['pclass'].min()) / (train['pclass'].max() - train['pclass'].min())
    print("Modified DataFrame:")
    print(train)

Original DataFrame:
   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.4           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.3          0.2  setosa
4           5.1          3.6           1.4          0.2  setosa
Columns 'pclass' and 'age' must exist in the dataset.

In [94]:
df['Age'] = df.groupby('Sex')['Age'].transform(lambda x: x.fillna(x.mean()))
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [100]:
df['Pclass']=(df['Pclass']-df['Pclass'].min()) / (df['Pclass'].max() - df['Pclass'].min())
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,1.0,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,NaN,S
1,2,1,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,1.0,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,1.0,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,NaN,S
5,6,0,1.0,"Moran, Mr. James",male,30.726645,0,0,330877,8.4583,NaN,Q
6,7,0,0.0,"McCarthy, Mr. Timothy J",male,54.000000,0,0,17463,51.8625,E46,S
7,8,0,1.0,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,21.0750,NaN,S
8,9,1,1.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.000000,0,2,347742,11.1333,NaN,S
9,10,1,0.5,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.000000,1,0,237736,30.0708,NaN,C